### ISSUE TITLE
dailyBr0t

### ISSUE THREAD

**Issue by Bachstelze** [pr0stats/pr0kular-feedback#4]
bei dailyBr0t (https://github.com/Bachstelze/pr0gramm_spider/tree/master/Daily) werden noch andere Eigenschaften, wie z.B. die besten Soßen analysiert

**Comment by pr0stats** [comment]
Sehr cool, das wäre doch was für https://holzmaster.github.io/userscripts/ – am besten da mal einen Pull Request mit den entsprechenden Daten abgeben.
